### PR TITLE
import books

### PR DESCRIPTION
**Pull request by patricoferris**
Initial import of books from https://github.com/ocaml/ocaml.org/blob/190c9fb768473a9c09ac011adb6f6ed0db190025/site/learn/books.md

TODO: 
 - [x] Add all of the cover images

### CODE REVIEW

**Comment by tmattio** [comment]
Thanks @patricoferris!! Looking at the current book page (https://ocaml.org/learn/books.html), I think we'd also need the list of URLs for the book (e.g. Amazon, O'Reilly, etc.)

**Comment by tmattio** [comment]
Oh, I missed that they are included in the body of the markdown, sorry! Do you think they could be provided as metadata instead?

**Comment by patricoferris** [comment]
Yeah that sounds more reasonable, I'll create a follow up issue to do that 👍

**Comment by tmattio** [comment]
Also, we probably want to provide a French version of the books. It's not available currently, but let's add the existing markdown in an `en` subdirectory?

**Comment by tmattio** [comment]
Also (I promise, last one! 😄), do you mind if we keep all of the images and assets in `media` for now (can be in subdirectories), it's a bit less work for me with the preview app 🙂

**Comment by patricoferris** [comment]
> Also, we probably want to provide a French version of the books. It's not available currently, but let's add the existing markdown in an en subdirectory?

I guess there's nothing wrong with that for future-proofing sake. I think the focus of translations will be on the content that will have the most value. In particular the tutorials, BKMs etc. and if we have time we can circle back to things like the books. But putting it into an `en` directory should be fine even if we don't get around to that :)) 

> Also (I promise, last one! 😄), do you mind if we keep all of the images and assets in media for now (can be in subdirectories), it's a bit less work for me with the preview app 🙂

media + subdirectories sounds good 👍   -- can you make those changes in line with the preview app?

**Comment by tmattio** [comment]
> can you make those changes in line with the preview app?

Absolutely 👍

**Pull request merged**
