### PR TITLE
Import workshop data 2008-17

### PR DESCRIPTION
**Pull request by f-ludlam**
Preview to check what I am working on is right

### CODE REVIEW

**Comment by patricoferris** [comment]
Thanks @f-ludlam this looks fantastic 🎉 ! All of the information looks good and the extra metadata looks useful too. As we discussed offline since we're adding new fields to the metadata we'll also have to update the types too at some point (the CI should fail because of this, so don't worry about any red crosses on this PR). 

It might be best to carry on importing the rest of the data, adding new fields as you come across new metadata that needs to be encoded and then at the end we can do one pass over the types to update them with the new fields, or we can do it incrementally adding say `2015-17` + types now ? 

To provide some extra information about what I mean by types, currently the metadata for the workshops is described by OCaml types here: https://github.com/ocaml/ood/blob/main/src/ood/workshop.ml and you can see for example we have a type for the presentation that looks like: 

```ocaml
type presentation = {
    title : string;
    authors : string list;
    link : string option;
    video : string option;
    slides : string option;
    additional_links : string list option;
  }
```

Hopefully the correspondence with the yaml is self-evident. You've added a new field called `type` to describe if the presentation was a `Poster` or not, which is great, but we'll need to update all of the workshop types to match it so we generate and parse the data correctly at some point :)) Let me know if you want to carry on importing or if want some help with the OCaml side of things.

**Comment by patricoferris** [comment]
Just need a `make fmt` and we should be set, thanks @f-ludlam :))

**Comment by patricoferris** [comment]
Fantastic! The CI is actually now broken because it is incompatible with opam 2.1.0. There's a fix upstream, but I checked this out locally and tested and looks good to me. Merging now :)

**Comment by avsm** [comment]
Excellent work, @f-ludlam!

**Pull request merged**
