### PR TITLE
Add success stories

### PR DESCRIPTION
**Pull request by tmattio**
*Inadvertently pushed this in `main` and reverted. Sorry for the inconvenience.*

This ports the success stories from the `ocaml.org` website.

I opted for the simplest type:

```ocaml
type t = { title : string; image : string option }
```

Since the other fields suggested in #17 are not present on the other website. @patricoferris do you recommend adding them nonetheless?

**To do**

- [x] I copied the text and manually from the website, not knowning there already was a markdown version of the content. I should copy paste it from the previous markdown again to reduce the odds of manual error.
- [x] Add a field for the image link

### CODE REVIEW

**Comment by patricoferris** [comment]
Thanks @tmattio! This is a good first step, maybe just create an issue afterward to follow up on adding some extra metadata but it doesn't need to happen in this PR. 

Not sure we need the Makefile though 😁

**Comment by tmattio** [comment]
Thanks, will open an issue 🙂 

> Not sure we need the Makefile though

`dune build @fmt --auto-promote` and co are really long commands for things typically ran 20 times/min 😅 
I can open another PR for this if you want, it's not really related to this work?

**Comment by patricoferris** [comment]
Oh sorry I just thought it was a mistake because I saw `bash -c "cp $$(opam exec -- which spin) /usr/local/bin/spin"` and assumed it was something from a spin template committed by mistake, apologies. The Makefile is v. welcome! Thanks

**Comment by tmattio** [comment]
Oops, I copied the Makefile from spin, missed that specific bit, I removed it 🙂

**Comment by tmattio** [comment]
@patricoferris I replaced the content copied from the website with a copy of the original markdown. I'm not sure I understood the manual fixes to apply to the old markdown you mentioned this morning: could you check that I didn't leave any incompatible syntax?

**Comment by patricoferris** [comment]
This looks great thanks. What we discussed was related to #15 where the particular markdown syntax used interacts strangely with mdx trying to run the code blocks (at least from the little experimentation I did). I'm not sure where to place the images, I don't know if a global `media` directory is better than a specific `data/success_stories/img` directory. NetlifyCMS prefers the former but we might move away from this.

**Comment by tmattio** [comment]
> NetlifyCMS prefers the former but we might move away from this.

I imagine we can let it become painful and it won't be too much trouble to change down the line if we're referencing the images with their path in the metadata

**Comment by tmattio** [comment]
This is now ready to merge if you want @patricoferris 🙂

**Comment by patricoferris** [comment]
Thanks for this :))

**Pull request merged**
