### PR TITLE
Add iitm

### PR DESCRIPTION
**Pull request by kayceesrk**
I've added link to the IITM course which uses OCaml for teaching functional programming.

### CODE REVIEW

**Comment by patricoferris** [comment]
Thanks @kayceesrk ! We need a `dune build` to regenerate the static OCaml modules in `src/ood` to include IITM -- I can do that and push here if that'll be easier for you (in the future to ease the workflow it might be a good idea if we automate this in CI) ?

**Comment by avsm** [comment]
I pushed the crunch to kc's branch, so this should be mergeable.

**Comment by patricoferris** [comment]
Cheers @avsm !

**Comment by kayceesrk** [comment]
Thanks @avsm and @patricoferris

**Pull request merged**
