### PR TITLE
Update CI to `setup-ocaml@v2`

### PR DESCRIPTION
**Pull request by tmattio**

### CODE REVIEW

**Comment by tmattio** [comment]
I am not sure why the build would fail with:

```
### output ###
# File "dune", line 1, characters 0-136:
# 1 | (rule
# 2 |  (deps ./src/bin/main.exe)
# 3 |  (targets config.output)
# 4 |  (action
# 5 |   (with-stdout-to
# 6 |    %{targets}
# 7 |    (run ./src/bin/main.exe config))))
# Error: No rule found for src/bin/main.exe
```

I've added the dependency on `src/bin/main.exe` explicitly, but it still fails with this `no rule` error.

**Comment by patricoferris** [comment]
Seems to be because before we installed via `dune build @install` and the dependencies where installed with `--deps-only` so afaict the `-t` (aka `--with-test`) was doing nothing... a quick (and probably insufficient) fix would be to remove `--with-test` from the installation command and let `dune build @runtest` do those checks?

**Comment by patricoferris** [comment]
The approach used before in the CI script was a version of what is used in ocaml-ci (e.g. https://ci.ocamllabs.io/github/mirage/capnp-rpc/commit/38c76c25fbd95b5e1dd27b1c6a4e46479ba8dee3/variant/debian-10-4.12) although the pinning is mainly for the depext which is not a problem in `opam.2.1.0`

**Comment by tmattio** [comment]
There were some missing `package` stanzas in the runtest rules, I added the correct dependencies for the different rules.
As part of tracking down the issue, I took the liberty of moving the source code to subdirectories in `src/`, I found it a bit easier to understand the directory structure this way. But if you prefer, I can rever this part 🙂

**Comment by patricoferris** [comment]
Thanks for fixing this, the project structure looks cleaner. Will the change (in particular moving the ReScript package) break anything upstream if we merge, I don't think it should?

**Comment by tmattio** [comment]
I don't think it should, I updated the list of directories to look for in `bsconfig.json`, and AFAIU, ReScript does not care about the directory structure (i.e. all of the modules are available at the top level, no matter where they are located on the filesystem)

**Comment by patricoferris** [comment]
Great, thanks again! Feel free to merge whenever you are ready (i.e. if this is inline with what you need for #22) :))

**Comment by tmattio** [comment]
Great, I'll merge now and rebase #22, which should be ready to merge as well.
I'll add you as a reviewer and wait for approvals for the next PRs if you let me merge 🙂

**Pull request merged**
